image: 'node:latest'

pages:
    stage: deploy
    script:
        - npm install
        - NODE_ENV=production npm run build
    artifacts:
        paths:
            - public
    only:
        - main
